config/routes.rb
Rails.application.routes.draw do
  get 'event_wizard/info'
  post 'event_wizard/info' => 'event_wizard#post_info'

  get 'event_wizard/participants'

  get 'event_wizard/constraints'

  get 'event_wizard/confirm'

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  resources :events do
    resource :draw
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true

  has_many :participants
  accepts_nested_attributes_for :participants,
    :reject_if => :all_blank,
    :allow_destroy => true

  has_many :constraints
  accepts_nested_attributes_for :constraints,
    :reject_if => :all_blank,
    :allow_destroy => true

  has_many :draws

  before_create :randomize_id

  def select_participants
    self.participants.collect { |x| [x.name, x.id] }
  end

  def draw_order
    participants = self.participants
    participants = participants.collect { |x| x }
    draw = []
    max_tries = 1000
    max_tries.times do
      participants.shuffle!
      draw = participants.zip(participants.rotate)
      if all_constraints_ok draw
        return draw
      end
    end
    nil
  end

  private

    def all_constraints_ok(draw)
      draw.all? do |(giver, receiver)|
        self.constraints.all? { |c| c.respected_by(giver, receiver) }
      end
    end

    def randomize_id
      begin
        self.id = SecureRandom.random_number(1_000_000)
      end while Event.where(id: self.id).exists?
    end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new event_params
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    if @event.draws.any?
      flash[:info] = "The ballots for this event have already been drawn."
    end
  end

  def edit
    @event = Event.find(params[:id])
    if @event.draws.any?
      redirect_to @event
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.draws.any?
      return (redirect_to @event)
    end
    if @event.update(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'edit'
    end
  end

  private

    def event_params
      params.require(:event).permit(:title,
                                    :amount,
                                    :locale,
                                    participants_attributes: [:id, :_destroy, :name, :email],
                                    constraints_attributes: [:id, :_destroy, :one_id, :other_id]
                                   )
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def locales_and_names
    locales = [:fr, :en]
    locales.collect do |l|
      name = I18n.t :locale_name, locale: l
      [name, l]
    end
  end
end

app/views/events/_constraint_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <%= f.select :one_id, @event.select_participants %>
    -
    <%= f.select :other_id, @event.select_participants %>
  
    <%= link_to_remove_association "remove", f %>
  </div>
</li>

app/views/events/_participant_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :email, "Email" %>
    <%= f.email_field :email %>
  
    <%= link_to_remove_association "remove", f %>
  </div>
</li>

app/views/events/edit.html.erb
<h1>Edit: <%= @event.title %></h1>

<%= form_for @event do |f| %>
<div class="container">
  <%= render '/shared/form_errors' %>
  <fieldset>
    <ul>
      <li class="control-group">
        <%= f.label :title, "Title" %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </li>
      <li class="control-group">
        <%= f.label :amount, "Amount" %>
        <div class="controls">
          <%= f.text_field :amount %>
        </div>
      </li>
      <li class="control-group">
        <%= f.label :locale, "Language" %>
        <div class="controls">
          <%= f.select :locale, locales_and_names %>
        </div>
      </li>
    </ul>
  </fieldset>

  <div class="col-md-7">
  <h2>Participants</h2>

  <p>
    List the participants to this event, including you. Make sure that emails are
    valid since these are the addresses where the results will be sent to.
  </p>

  <fieldset id="event-participants">
    <ul>
      <%= f.fields_for :participants do |participant| %>
        <%= render 'participant_fields', f: participant %>
      <% end %>
    </ul>
    <%= link_to_add_association 'Add participant', f, :participants,
      'data-association-insertion-node' => "#event-participants ul",
      'data-association-insertion-method' => "append",
      :wrap_object => Proc.new {|participant| participant.build_event; participant }
    %>
  </fieldset>
  </div>

  <div class="col-md-5">
  <h2>Constraints</h2>

  <p>
    Adding a constraint between Alice and Bob will make sure that Alice will not
    have to get a gift for Bob, and Bob does not have to get a gift for Alice.
  </p>
  <p>
    In case there are too many constraints and it is impossible to find a
    solution, you will be informed and no mail will be sent.
  </p>
  <p>
    After you add participants, you will need to update the event and come back
    to this edit page in order to be able to add constraints.
  </p>

  <fieldset id="event-constraints">
    <ul>
      <%= f.fields_for :constraints do |constraint| %>
        <%= render 'constraint_fields', f: constraint %>
      <% end %>
    </ul>
    <%= link_to_add_association 'Add constraint', f, :constraints,
      'data-association-insertion-node' => "#event-constraints ul",
      'data-association-insertion-method' => "append",
      :wrap_object => Proc.new {|constraint| constraint.build_event; constraint }
    %>
  </fieldset>
  </div>

</div>
<%= f.submit %>
<% end %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create an event</h1>

    <%= form_for(@event) do |f| %>
      <%= render '/shared/form_errors' %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <p class="help-block">
      Find a name that is not too generic so that participants can know which
      event it is.
      </p>

      <div class="form-group">
        <%= f.label :amount %>
        <%= f.text_field :amount, class: 'form-control' %>
      </div>
      <p class="help-block">
      This is the suggested amount people are encouraged to spend on a gift.
      </p>

      <div class="form-group">
        <%= f.label :locale, "Language" %>
        <%= f.select :locale, locales_and_names, class: 'form-control' %>
      </div>
      <p class="help-block">
      Participants will receive an email in this language.
      </p>

      <%= f.submit "Create an event", class: "btn btn-primary" %>
    <% end %>

    <div class="event-create-preview">
      <h2>Preview</h2>

      <h3 class="preview-en">
        Subject: <span class="preview-title"></span> - gift attribution for François
      </h3>

      <h3 class="preview-fr">
        Sujet: <span class="preview-title"></span> - attribution du cadeau pour François
      </h3>

      <h3>Message</h3>

      <div class="preview-en">
        <p>
          Hello François,
        </p>

        <p>
        You are taking part in "<span class="preview-title"></span>".
        </p>

        <p>
        This is a "Secret Santa" event, where participants are asked to get a gift for
        another random person. You give a gift to someone and you get a gift from
        someone else.
        </p>

        <p>
        You should get a gift for:
        </p>

        <p>
        <b>Julie</b>
        </p>

        <div class="preview-amount-div">
        The suggested amount for the gift is: <b class="preview-amount"></b>.
        </div>
      </div>

      <div class="preview-fr">
        <p>
          Bonjour François,
        </p>

        <p>
        Vous participez à "<span class="preview-title"></span>".
        </p>

        <p>
        C'est un "Secret Santa", où on demande aux participants de faire un cadeau à une
        autre personne au hasard. Chacun fait un cadeau à quelqu'un, et reçoit un cadeau
        de quelqu'un d'autre.
        </p>

        <p>
        Vous devez faire un cadeau à:
        </p>

        <p>
        <b>Julie</b>
        </p>

        <div class="preview-amount-div">
        Le montant suggéré est de: <b class="preview-amount"></b>.
        </div>
      </div>

    </div>

  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<% if @event.amount? and not @event.amount.empty? %>
  <b>Amount:</b> <%= @event.amount %>
<% end %>

<div class="container">

  <div class="col-md-4 col-md-offset-2">
    <h2>Participants: <%= @event.participants.length %></h2>

    <ul>
      <% for p in @event.participants %>
        <li>
          <%= p.name %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-4">
    <h2>Constraints</h2>

    <% if @event.constraints.empty? %>
      No constraints.
    <% elsif %>
      <ul>
        <% for c in @event.constraints %>
          <li>
            <%= c.one.name %> - <%= c.other.name %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

</div>

<% if @event.draws.empty? %>
  <%= link_to 'Edit this event', edit_event_path(@event) %>

  <%= link_to 'Draw the ballots', event_draw_path(@event) %>
<% end %>